// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var Data_Function_Uncurried = require("../Data.Function.Uncurried/index.js");
var Data_Monoid = require("../Data.Monoid/index.js");
var Data_Semigroup = require("../Data.Semigroup/index.js");
var semigroupJSX = new Data_Semigroup.Semigroup(function (a) {
    return function (b) {
        return $foreign.fragment([ a, b ]);
    };
});
var monoidJSX = new Data_Monoid.Monoid(function ($dollar__unused) {
    return semigroupJSX;
}, $foreign.empty);
var element = Data_Function_Uncurried.runFn2($foreign.element_);
module.exports = {
    element: element,
    semigroupJSX: semigroupJSX,
    monoidJSX: monoidJSX,
    empty: $foreign.empty,
    fragment: $foreign.fragment
};
