// Generated by purs version 0.13.6
"use strict";
var React_Basic = require("../React.Basic/index.js");
var React_Basic_DOM_Internal = require("../React.Basic.DOM.Internal/index.js");
var tspan$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("tspan");
};
var tspan = function (dictUnion) {
    return React_Basic.element(tspan$prime());
};
var text$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("text");
};
var text = function (dictUnion) {
    return React_Basic.element(text$prime());
};
var svg$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("svg");
};
var svg = function (dictUnion) {
    return React_Basic.element(svg$prime());
};
var stop$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("stop");
};
var stop = function (dictUnion) {
    return React_Basic.element(stop$prime());
};
var radialGradient$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("radialGradient");
};
var radialGradient = function (dictUnion) {
    return React_Basic.element(radialGradient$prime());
};
var path$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("path");
};
var path = function (dictUnion) {
    return React_Basic.element(path$prime());
};
var linearGradient$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("linearGradient");
};
var linearGradient = function (dictUnion) {
    return React_Basic.element(linearGradient$prime());
};
var g$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("g");
};
var g = function (dictUnion) {
    return React_Basic.element(g$prime());
};
var ellipse$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("ellipse");
};
var ellipse = function (dictUnion) {
    return React_Basic.element(ellipse$prime());
};
var defs$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("defs");
};
var defs = function (dictUnion) {
    return React_Basic.element(defs$prime());
};
var clipPath$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("clipPath");
};
var clipPath = function (dictUnion) {
    return React_Basic.element(clipPath$prime());
};
var circle$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("circle");
};
var circle = function (dictUnion) {
    return React_Basic.element(circle$prime());
};
module.exports = {
    circle: circle,
    "circle'": circle$prime,
    clipPath: clipPath,
    "clipPath'": clipPath$prime,
    defs: defs,
    "defs'": defs$prime,
    ellipse: ellipse,
    "ellipse'": ellipse$prime,
    g: g,
    "g'": g$prime,
    linearGradient: linearGradient,
    "linearGradient'": linearGradient$prime,
    path: path,
    "path'": path$prime,
    radialGradient: radialGradient,
    "radialGradient'": radialGradient$prime,
    stop: stop,
    "stop'": stop$prime,
    svg: svg,
    "svg'": svg$prime,
    text: text,
    "text'": text$prime,
    tspan: tspan,
    "tspan'": tspan$prime
};
