// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var Control_Promise = require("../Control.Promise/index.js");
var URL = function (x) {
    return x;
};
var statusCode = function (response) {
    return response.status;
};
var postMethod = "POST";
var json = function (res) {
    return Control_Promise.toAffE($foreign.jsonImpl(res));
};
var fromRecord = function (dictHomogeneous) {
    return $foreign.fromRecordImpl;
};
var makeHeaders = function (dictHomogeneous) {
    return fromRecord();
};
var fetch = function (impl) {
    return function (dictUnion) {
        return function (url$prime) {
            return function (opts) {
                return Control_Promise.toAffE($foreign["_fetch"](impl)(url$prime)(opts));
            };
        };
    };
};
module.exports = {
    URL: URL,
    postMethod: postMethod,
    fetch: fetch,
    json: json,
    makeHeaders: makeHeaders,
    statusCode: statusCode
};
