// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
module.exports = {
    mkFn2: $foreign.mkFn2,
    runFn2: $foreign.runFn2,
    runFn3: $foreign.runFn3,
    runFn4: $foreign.runFn4
};
