// Generated by purs version 0.13.6
"use strict";
var Color = require("../Color/index.js");
var Data_Array_NonEmpty = require("../Data.Array.NonEmpty/index.js");
var systemFontStack = [ "-apple-system", "BlinkMacSystemFont", "Helvetica", "Arial", "sans-serif" ];
var darkTheme = {
    backgroundColour: Color.hsl(220.0)(0.42)(0.13),
    textColour: Color.hsl(225.0)(0.28)(0.9),
    interfaceColour: Color.hsl(225.0)(0.48)(0.12),
    highlightColour: Color.rgb(209)(51)(225),
    altHighlightColour: Color.hsl(84.0)(0.617)(0.631),
    textFontFamily: Data_Array_NonEmpty["cons'"]("Rubik")(systemFontStack),
    headingFontFamily: Data_Array_NonEmpty["cons'"]("Rubik")(systemFontStack),
    codeFontFamily: Data_Array_NonEmpty["cons'"]("'VictorMono'")([ "monospace" ]),
    yellow: Color.rgb(255)(235)(149),
    green: Color.hsl(84.0)(0.617)(0.631),
    pink: Color.hsl(276.0)(0.677)(0.745),
    orange: Color.rgb(255)(203)(139),
    turquoise: Color.rgb(127)(219)(202),
    red: Color.rgb(255)(88)(116),
    blue: Color.rgb(130)(170)(255),
    white: Color.rgb(250)(250)(250),
    measure: "60ch",
    borderThin: "0.125rem"
};
module.exports = {
    systemFontStack: systemFontStack,
    darkTheme: darkTheme
};
