// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var Data_Functor = require("../Data.Functor/index.js");
var Data_Nullable = require("../Data.Nullable/index.js");
var Effect = require("../Effect/index.js");
var getElementById = function (eid) {
    var $414 = Data_Functor.map(Effect.functorEffect)(Data_Nullable.toMaybe);
    var $415 = $foreign["_getElementById"](eid);
    return function ($416) {
        return $414($415($416));
    };
};
module.exports = {
    getElementById: getElementById
};
