// Generated by purs version 0.13.6
"use strict";
var Data_List_Types = require("../Data.List.Types/index.js");
var Data_NonEmpty = require("../Data.NonEmpty/index.js");
var singleton = (function () {
    var $180 = Data_NonEmpty.singleton(Data_List_Types.plusList);
    return function ($181) {
        return Data_List_Types.NonEmptyList($180($181));
    };
})();
module.exports = {
    singleton: singleton
};
