// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var Unsafe_Coerce = require("../Unsafe.Coerce/index.js");
var toEventTarget = Unsafe_Coerce.unsafeCoerce;
module.exports = {
    toEventTarget: toEventTarget,
    document: $foreign.document,
    scrollY: $foreign.scrollY
};
