// Generated by purs version 0.13.6
"use strict";
var IxApply = function (IxFunctor0, iapply) {
    this.IxFunctor0 = IxFunctor0;
    this.iapply = iapply;
};
module.exports = {
    IxApply: IxApply
};
