// Generated by purs version 0.13.6
"use strict";
var Tuple = (function () {
    function Tuple(value0, value1) {
        this.value0 = value0;
        this.value1 = value1;
    };
    Tuple.create = function (value0) {
        return function (value1) {
            return new Tuple(value0, value1);
        };
    };
    return Tuple;
})();
var snd = function (v) {
    return v.value1;
};
var fst = function (v) {
    return v.value0;
};
module.exports = {
    Tuple: Tuple,
    fst: fst,
    snd: snd
};
