// Generated by purs version 0.13.6
"use strict";
var Control_Monad_Except_Trans = require("../Control.Monad.Except.Trans/index.js");
var Data_Identity = require("../Data.Identity/index.js");
var Data_Newtype = require("../Data.Newtype/index.js");
var withExcept = Control_Monad_Except_Trans.withExceptT(Data_Identity.functorIdentity);
var runExcept = (function () {
    var $82 = Data_Newtype.unwrap(Data_Identity.newtypeIdentity);
    return function ($83) {
        return $82(Control_Monad_Except_Trans.runExceptT($83));
    };
})();
var mapExcept = function (f) {
    return Control_Monad_Except_Trans.mapExceptT((function () {
        var $84 = Data_Newtype.unwrap(Data_Identity.newtypeIdentity);
        return function ($85) {
            return Data_Identity.Identity(f($84($85)));
        };
    })());
};
module.exports = {
    runExcept: runExcept,
    mapExcept: mapExcept,
    withExcept: withExcept
};
