// Generated by purs version 0.13.6
"use strict";
var Control_Applicative = require("../Control.Applicative/index.js");
var Data_Array = require("../Data.Array/index.js");
var Data_Foldable = require("../Data.Foldable/index.js");
var Data_Monoid = require("../Data.Monoid/index.js");
var Data_Semigroup = require("../Data.Semigroup/index.js");
var Data_Symbol = require("../Data.Symbol/index.js");
var JSS = require("../JSS/index.js");
var React_Basic_DOM = require("../React.Basic.DOM/index.js");
var React_Basic_DOM_Generated = require("../React.Basic.DOM.Generated/index.js");
var React_Basic_Hooks = require("../React.Basic.Hooks/index.js");
var React_Basic_Hooks_Internal = require("../React.Basic.Hooks.Internal/index.js");
var Record_Extra = require("../Record.Extra/index.js");
var Type_Equality = require("../Type.Equality/index.js");
var Yoga_Theme_Styles = require("../Yoga.Theme.Styles/index.js");
var H1 = (function () {
    function H1() {

    };
    H1.value = new H1();
    return H1;
})();
var H2 = (function () {
    function H2() {

    };
    H2.value = new H2();
    return H2;
})();
var H3 = (function () {
    function H3() {

    };
    H3.value = new H3();
    return H3;
})();
var H4 = (function () {
    function H4() {

    };
    H4.value = new H4();
    return H4;
})();
var Subheading = (function () {
    function Subheading() {

    };
    Subheading.value = new Subheading();
    return Subheading;
})();
var mkH = function __do() {
    var useStyles = Yoga_Theme_Styles.makeStylesJSS()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "common";
    }))()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "h1";
    }))()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "h2";
    }))()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "h3";
    }))()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "h4";
    }))()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "h5";
    }))()(Record_Extra.mapRecordNil)()())()())()())()())()())()())(JSS.jssClasses()(function (v) {
        return {
            common: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "color";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "fontFamily";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsNil)))()())({
                color: v.textColour,
                fontFamily: v.headingFontFamily
            }),
            h1: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "fontSize";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "letterSpacing";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "margin";
            }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "padding";
            }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "textTransform";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsNil))))))()())({
                textTransform: "uppercase",
                fontSize: "3.6em",
                letterSpacing: "0.07em",
                margin: 0,
                padding: 0
            }),
            h2: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "fontSize";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "letterSpacing";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "margin";
            }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "padding";
            }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "textTransform";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsNil))))))()())({
                textTransform: "uppercase",
                fontSize: "3em",
                letterSpacing: "0.05em",
                margin: 0,
                padding: 0
            }),
            h3: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "fontSize";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "margin";
            }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "padding";
            }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsNil))))()())({
                fontSize: "2.2em",
                margin: 0,
                padding: 0
            }),
            h4: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "fontSize";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "margin";
            }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "padding";
            }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsNil))))()())({
                fontSize: "1.5em",
                margin: 0,
                padding: 0
            }),
            h5: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "color";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "fontSize";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "margin";
            }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "padding";
            }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsNil)))))()())({
                fontSize: "1.0em",
                margin: 0,
                padding: 0,
                color: v.textColourLighter
            })
        };
    }))();
    return React_Basic_Hooks.component()()()("Heading")(function (v) {
        return React_Basic_Hooks_Internal.bind(React_Basic_Hooks_Internal.ixBindRender)(useStyles({}))(function (classes) {
            var elem = (function () {
                if (v.level instanceof H1) {
                    return React_Basic_DOM_Generated.h1();
                };
                if (v.level instanceof H2) {
                    return React_Basic_DOM_Generated.h2();
                };
                if (v.level instanceof H3) {
                    return React_Basic_DOM_Generated.h3();
                };
                if (v.level instanceof H4) {
                    return React_Basic_DOM_Generated.h4();
                };
                if (v.level instanceof Subheading) {
                    return React_Basic_DOM_Generated.h5();
                };
                throw new Error("Failed pattern match at Yoga.Typography.Header (line 72, column 14 - line 77, column 27): " + [ v.level.constructor.name ]);
            })();
            var specificClassName = (function () {
                if (v.level instanceof H1) {
                    return classes.h1;
                };
                if (v.level instanceof H2) {
                    return classes.h2;
                };
                if (v.level instanceof H3) {
                    return classes.h3;
                };
                if (v.level instanceof H4) {
                    return classes.h4;
                };
                if (v.level instanceof Subheading) {
                    return classes.h5;
                };
                throw new Error("Failed pattern match at Yoga.Typography.Header (line 79, column 27 - line 84, column 33): " + [ v.level.constructor.name ]);
            })();
            return Control_Applicative.pure(React_Basic_Hooks_Internal.applicativeRender(Type_Equality.refl))(elem({
                className: Data_Foldable.intercalate(Data_Foldable.foldableArray)(Data_Monoid.monoidString)(" ")(Data_Semigroup.append(Data_Semigroup.semigroupArray)([ classes.common, specificClassName ])(Data_Array.fromFoldable(Data_Foldable.foldableMaybe)(v.className))),
                children: [ React_Basic_DOM.text(v.text) ]
            }));
        });
    })();
};
module.exports = {
    H1: H1,
    H2: H2,
    H3: H3,
    H4: H4,
    Subheading: Subheading,
    mkH: mkH
};
