// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var Partial = require("../Partial/index.js");
var unsafeCrashWith = function (msg) {
    return $foreign.unsafePartial(function (dictPartial) {
        return Partial.crashWith()(msg);
    });
};
module.exports = {
    unsafeCrashWith: unsafeCrashWith,
    unsafePartial: $foreign.unsafePartial
};
