// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var Control_Applicative = require("../Control.Applicative/index.js");
var Control_Bind = require("../Control.Bind/index.js");
var Control_Promise = require("../Control.Promise/index.js");
var Data_Eq = require("../Data.Eq/index.js");
var Data_Function = require("../Data.Function/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Data_Monoid = require("../Data.Monoid/index.js");
var Data_Symbol = require("../Data.Symbol/index.js");
var Data_Unit = require("../Data.Unit/index.js");
var Effect = require("../Effect/index.js");
var Effect_Aff = require("../Effect.Aff/index.js");
var Effect_Class = require("../Effect.Class/index.js");
var Effect_Uncurried = require("../Effect.Uncurried/index.js");
var Foreign = require("../Foreign/index.js");
var JSS = require("../JSS/index.js");
var React_Basic = require("../React.Basic/index.js");
var React_Basic_DOM_Generated = require("../React.Basic.DOM.Generated/index.js");
var React_Basic_Hooks = require("../React.Basic.Hooks/index.js");
var React_Basic_Hooks_Aff = require("../React.Basic.Hooks.Aff/index.js");
var React_Basic_Hooks_Internal = require("../React.Basic.Hooks.Internal/index.js");
var Record_Extra = require("../Record.Extra/index.js");
var Type_Equality = require("../Type.Equality/index.js");
var Yoga_Theme_Styles = require("../Yoga.Theme.Styles/index.js");
var monacoEditor = function (dictUnion) {
    return Control_Bind.bind(Effect_Aff.bindAff)(Effect_Class.liftEffect(Effect_Aff.monadEffectAff)($foreign.monacoEditorImpl))(function (prom) {
        return Control_Promise.toAff(prom);
    });
};
var lightThemeName = "VSCode";
var darkThemeName = "NightOwl";
var initEditor = function (monaco) {
    return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)($foreign.defineThemeImpl(monaco)(darkThemeName)($foreign.nightOwlTheme))(function ($dollar__unused) {
        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)($foreign.defineThemeImpl(monaco)(lightThemeName)($foreign.vsCodeTheme))(function ($dollar__unused) {
            return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)($foreign.registerLanguageImpl(monaco)("purescript"))(function ($dollar__unused) {
                return $foreign.setMonarchTokensProviderImpl(monaco)("purescript")($foreign.purescriptSyntax);
            });
        });
    });
};
var mkEditor = function __do() {
    var useStyles = Yoga_Theme_Styles.makeStylesJSS()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
        return "wrapper";
    }))()(Record_Extra.mapRecordNil)()())(JSS.jssClasses()(function (v) {
        return {
            wrapper: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "backgroundColor";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "boxSizing";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "margin";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "overflowY";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "width";
            }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsNil))))))()())({
                margin: "0",
                boxSizing: "border-box",
                width: "100%",
                overflowY: "hidden",
                backgroundColor: v.backgroundColour
            })
        };
    }))();
    return React_Basic_Hooks.component()()()("Editor")(function (v) {
        return React_Basic_Hooks_Internal.bind(React_Basic_Hooks_Internal.ixBindRender)(useStyles({}))(function (classes) {
            return React_Basic_Hooks_Internal.bind(React_Basic_Hooks_Internal.ixBindRender)(React_Basic_Hooks.useState(Data_Maybe.Nothing.value))(function (v1) {
                return React_Basic_Hooks_Internal.discard(React_Basic_Hooks_Internal.ixBindRender)(React_Basic_Hooks_Aff.useAff(Data_Eq.eqUnit)(Data_Unit.unit)(Control_Bind.bind(Effect_Aff.bindAff)(monacoEditor())(function (eddy) {
                    return Effect_Class.liftEffect(Effect_Aff.monadEffectAff)(v1.value1(Data_Function["const"](new Data_Maybe.Just(eddy))));
                })))(function ($dollar__unused) {
                    return React_Basic_Hooks_Internal.bind(React_Basic_Hooks_Internal.ixBindRender)(Yoga_Theme_Styles.useTheme)(function (theme) {
                        var themeName = (function () {
                            if (theme.isLight) {
                                return lightThemeName;
                            };
                            return darkThemeName;
                        })();
                        return Control_Applicative.pure(React_Basic_Hooks_Internal.applicativeRender(Type_Equality.refl))(React_Basic.fragment([ React_Basic_DOM_Generated.div()({
                            className: classes.wrapper,
                            children: [ Data_Maybe.maybe(Data_Monoid.mempty(React_Basic.monoidJSX))(function (editor) {
                                return React_Basic.element(editor)({
                                    theme: themeName,
                                    height: v.height,
                                    options: Foreign.unsafeToForeign({
                                        fontFamily: theme.codeFontFamily,
                                        fontLigatures: true,
                                        fontSize: "16pt",
                                        lineNumbers: "off",
                                        glyphMargin: false,
                                        folding: false,
                                        lineDecorationsWidth: 0,
                                        lineNumbersMinChars: 0,
                                        minimap: {
                                            enabled: false
                                        },
                                        scrollBeyondLastLine: false
                                    }),
                                    language: v.language,
                                    editorDidMount: function (e, v2) {
                                        return v.onLoad(e)();
                                    },
                                    editorWillMount: Effect_Uncurried.mkEffectFn1(initEditor)
                                });
                            })(v1.value0) ]
                        }) ]));
                    });
                });
            });
        });
    })();
};
module.exports = {
    monacoEditor: monacoEditor,
    darkThemeName: darkThemeName,
    lightThemeName: lightThemeName,
    initEditor: initEditor,
    mkEditor: mkEditor,
    monacoEditorImpl: $foreign.monacoEditorImpl,
    defineThemeImpl: $foreign.defineThemeImpl,
    nightOwlTheme: $foreign.nightOwlTheme,
    vsCodeTheme: $foreign.vsCodeTheme,
    getValue: $foreign.getValue,
    setValue: $foreign.setValue,
    purescriptSyntax: $foreign.purescriptSyntax,
    registerLanguageImpl: $foreign.registerLanguageImpl,
    setMonarchTokensProviderImpl: $foreign.setMonarchTokensProviderImpl
};
