// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var Eq = function (eq) {
    this.eq = eq;
};
var eqUnit = new Eq(function (v) {
    return function (v1) {
        return true;
    };
});
var eqString = new Eq($foreign.eqStringImpl);
var eqNumber = new Eq($foreign.eqNumberImpl);
var eqInt = new Eq($foreign.eqIntImpl);
var eqChar = new Eq($foreign.eqCharImpl);
var eq = function (dict) {
    return dict.eq;
};
module.exports = {
    Eq: Eq,
    eq: eq,
    eqInt: eqInt,
    eqNumber: eqNumber,
    eqChar: eqChar,
    eqString: eqString,
    eqUnit: eqUnit
};
