// Generated by purs version 0.13.6
"use strict";
var Control_Applicative = require("../Control.Applicative/index.js");
var Control_Bind = require("../Control.Bind/index.js");
var Data_Functor = require("../Data.Functor/index.js");
var Effect = require("../Effect/index.js");
var Web_Event_EventTarget = require("../Web.Event.EventTarget/index.js");
var Web_HTML = require("../Web.HTML/index.js");
var Web_HTML_Window = require("../Web.HTML.Window/index.js");
var eventType = "scroll";
var registerListener = function (listener) {
    return function __do() {
        var target = Data_Functor.mapFlipped(Effect.functorEffect)(Web_HTML.window)(Web_HTML_Window.toEventTarget)();
        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Web_Event_EventTarget.addEventListener(eventType)(listener)(false)(target))(function ($dollar__unused) {
            return Control_Applicative.pure(Effect.applicativeEffect)(Web_Event_EventTarget.removeEventListener(eventType)(listener)(false)(target));
        })();
    };
};
module.exports = {
    registerListener: registerListener
};
