// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var Semigroup = function (append) {
    this.append = append;
};
var semigroupString = new Semigroup($foreign.concatString);
var semigroupArray = new Semigroup($foreign.concatArray);
var append = function (dict) {
    return dict.append;
};
module.exports = {
    Semigroup: Semigroup,
    append: append,
    semigroupString: semigroupString,
    semigroupArray: semigroupArray
};
