// Generated by purs version 0.13.6
"use strict";
var Data_Function = require("../Data.Function/index.js");
var Effect_Uncurried = require("../Effect.Uncurried/index.js");
var handler_ = function ($370) {
    return Effect_Uncurried.mkEffectFn1(Data_Function["const"]($370));
};
module.exports = {
    handler_: handler_
};
