// Generated by purs version 0.13.6
"use strict";
var Parallel = function (Applicative1, Monad0, parallel, sequential) {
    this.Applicative1 = Applicative1;
    this.Monad0 = Monad0;
    this.parallel = parallel;
    this.sequential = sequential;
};
var sequential = function (dict) {
    return dict.sequential;
};
var parallel = function (dict) {
    return dict.parallel;
};
module.exports = {
    parallel: parallel,
    sequential: sequential,
    Parallel: Parallel
};
