// Generated by purs version 0.13.6
"use strict";
var Data_Ring = require("../Data.Ring/index.js");
var CommutativeRing = function (Ring0) {
    this.Ring0 = Ring0;
};
var commutativeRingNumber = new CommutativeRing(function ($dollar__unused) {
    return Data_Ring.ringNumber;
});
var commutativeRingInt = new CommutativeRing(function ($dollar__unused) {
    return Data_Ring.ringInt;
});
module.exports = {
    CommutativeRing: CommutativeRing,
    commutativeRingInt: commutativeRingInt,
    commutativeRingNumber: commutativeRingNumber
};
