// Generated by purs version 0.13.6
"use strict";
var Data_Foldable = require("../Data.Foldable/index.js");
var foldableNonEmptyArray = Data_Foldable.foldableArray;
module.exports = {
    foldableNonEmptyArray: foldableNonEmptyArray
};
