// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var withArray = function (f) {
    return function (xs) {
        return function __do() {
            var result = $foreign.thaw(xs)();
            var $dollar__unused = f(result)();
            return $foreign.unsafeFreeze(result)();
        };
    };
};
var push = function (a) {
    return $foreign.pushAll([ a ]);
};
module.exports = {
    withArray: withArray,
    push: push,
    pushAll: $foreign.pushAll,
    thaw: $foreign.thaw,
    unsafeFreeze: $foreign.unsafeFreeze
};
