// Generated by purs version 0.13.6
"use strict";
var Data_Array = require("../Data.Array/index.js");
var Unsafe_Coerce = require("../Unsafe.Coerce/index.js");
var unsafeFromArray = Unsafe_Coerce.unsafeCoerce;
var toArray = Unsafe_Coerce.unsafeCoerce;
var cons$prime = function (x) {
    return function (xs) {
        return unsafeFromArray(Data_Array.cons(x)(xs));
    };
};
var adaptAny = function (f) {
    return function ($119) {
        return f(toArray($119));
    };
};
var index = adaptAny(Data_Array.index);
module.exports = {
    toArray: toArray,
    "cons'": cons$prime,
    index: index
};
