// Generated by purs version 0.13.6
"use strict";
var RegexFlags = (function () {
    function RegexFlags(value0) {
        this.value0 = value0;
    };
    RegexFlags.create = function (value0) {
        return new RegexFlags(value0);
    };
    return RegexFlags;
})();
module.exports = {
    RegexFlags: RegexFlags
};
