// Generated by purs version 0.13.6
"use strict";
var Unsafe_Coerce = require("../Unsafe.Coerce/index.js");
var unsafeCreateDOMComponent = Unsafe_Coerce.unsafeCoerce;
module.exports = {
    unsafeCreateDOMComponent: unsafeCreateDOMComponent
};
