// Generated by purs version 0.13.6
"use strict";
var Control_Applicative = require("../Control.Applicative/index.js");
var Control_Apply = require("../Control.Apply/index.js");
var Control_Apply_Indexed = require("../Control.Apply.Indexed/index.js");
var Control_Bind_Indexed = require("../Control.Bind.Indexed/index.js");
var Data_Functor = require("../Data.Functor/index.js");
var Data_Functor_Indexed = require("../Data.Functor.Indexed/index.js");
var Effect = require("../Effect/index.js");
var Render = function (x) {
    return x;
};
var unsafeHook = Render;
var ixFunctorRender = new Data_Functor_Indexed.IxFunctor(function (f) {
    return function (v) {
        return Data_Functor.map(Effect.functorEffect)(f)(v);
    };
});
var ixApplyRender = new Control_Apply_Indexed.IxApply(function ($dollar__unused) {
    return ixFunctorRender;
}, function (v) {
    return function (v1) {
        return Control_Apply.apply(Effect.applyEffect)(v)(v1);
    };
});
var ixBindRender = new Control_Bind_Indexed.IxBind(function ($dollar__unused) {
    return ixApplyRender;
}, function (v) {
    return function (f) {
        return function __do() {
            var a = v();
            var v1 = f(a);
            return v1();
        };
    };
});
var functorRender = new Data_Functor.Functor(function (f) {
    return function (v) {
        return Data_Functor.map(Effect.functorEffect)(f)(v);
    };
});
var discard = function (dictIxBind) {
    return Control_Bind_Indexed.ibind(dictIxBind);
};
var coerceHook = function (dictNewtype) {
    return function (v) {
        return v;
    };
};
var bind = function (dictIxBind) {
    return Control_Bind_Indexed.ibind(dictIxBind);
};
var applyRender = function (dictTypeEquals) {
    return new Control_Apply.Apply(function ($dollar__unused) {
        return functorRender;
    }, function (v) {
        return function (v1) {
            return Control_Apply.apply(Effect.applyEffect)(v)(v1);
        };
    });
};
var applicativeRender = function (dictTypeEquals) {
    return new Control_Applicative.Applicative(function ($dollar__unused) {
        return applyRender(dictTypeEquals);
    }, function (a) {
        return Control_Applicative.pure(Effect.applicativeEffect)(a);
    });
};
module.exports = {
    coerceHook: coerceHook,
    unsafeHook: unsafeHook,
    bind: bind,
    discard: discard,
    ixFunctorRender: ixFunctorRender,
    ixApplyRender: ixApplyRender,
    ixBindRender: ixBindRender,
    functorRender: functorRender,
    applyRender: applyRender,
    applicativeRender: applicativeRender
};
