// Generated by purs version 0.13.6
"use strict";
var Data_Functor = require("../Data.Functor/index.js");
var Data_Monoid_Disj = require("../Data.Monoid.Disj/index.js");
var Newtype = function (unwrap, wrap) {
    this.unwrap = unwrap;
    this.wrap = wrap;
};
var wrap = function (dict) {
    return dict.wrap;
};
var unwrap = function (dict) {
    return dict.unwrap;
};
var newtypeDisj = new Newtype(function (v) {
    return v;
}, Data_Monoid_Disj.Disj);
var alaF = function (dictFunctor) {
    return function (dictFunctor1) {
        return function (dictNewtype) {
            return function (dictNewtype1) {
                return function (v) {
                    return function (f) {
                        var $243 = Data_Functor.map(dictFunctor1)(unwrap(dictNewtype1));
                        var $244 = Data_Functor.map(dictFunctor)(wrap(dictNewtype));
                        return function ($245) {
                            return $243(f($244($245)));
                        };
                    };
                };
            };
        };
    };
};
module.exports = {
    unwrap: unwrap,
    wrap: wrap,
    Newtype: Newtype,
    alaF: alaF,
    newtypeDisj: newtypeDisj
};
