// Generated by purs version 0.13.6
"use strict";
var TypeEquals = function (from, to) {
    this.from = from;
    this.to = to;
};
var refl = new TypeEquals(function (a) {
    return a;
}, function (a) {
    return a;
});
module.exports = {
    TypeEquals: TypeEquals,
    refl: refl
};
