// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var Show = function (show) {
    this.show = show;
};
var showString = new Show($foreign.showStringImpl);
var showNumber = new Show($foreign.showNumberImpl);
var showInt = new Show($foreign.showIntImpl);
var show = function (dict) {
    return dict.show;
};
module.exports = {
    Show: Show,
    show: show,
    showInt: showInt,
    showNumber: showNumber,
    showString: showString
};
