// Generated by purs version 0.13.6
"use strict";
var React_Basic = require("../React.Basic/index.js");
var React_Basic_DOM_Internal = require("../React.Basic.DOM.Internal/index.js");
var ul$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("ul");
};
var ul = function (dictUnion) {
    return React_Basic.element(ul$prime());
};
var nav$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("nav");
};
var nav = function (dictUnion) {
    return React_Basic.element(nav$prime());
};
var li$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("li");
};
var li = function (dictUnion) {
    return React_Basic.element(li$prime());
};
var header$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("header");
};
var header = function (dictUnion) {
    return React_Basic.element(header$prime());
};
var h5$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("h5");
};
var h5 = function (dictUnion) {
    return React_Basic.element(h5$prime());
};
var h4$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("h4");
};
var h4 = function (dictUnion) {
    return React_Basic.element(h4$prime());
};
var h3$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("h3");
};
var h3 = function (dictUnion) {
    return React_Basic.element(h3$prime());
};
var h2$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("h2");
};
var h2 = function (dictUnion) {
    return React_Basic.element(h2$prime());
};
var h1$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("h1");
};
var h1 = function (dictUnion) {
    return React_Basic.element(h1$prime());
};
var div$prime = function (dictUnion) {
    return React_Basic_DOM_Internal.unsafeCreateDOMComponent("div");
};
var div = function (dictUnion) {
    return React_Basic.element(div$prime());
};
module.exports = {
    div: div,
    "div'": div$prime,
    h1: h1,
    "h1'": h1$prime,
    h2: h2,
    "h2'": h2$prime,
    h3: h3,
    "h3'": h3$prime,
    h4: h4,
    "h4'": h4$prime,
    h5: h5,
    "h5'": h5$prime,
    header: header,
    "header'": header$prime,
    li: li,
    "li'": li$prime,
    nav: nav,
    "nav'": nav$prime,
    ul: ul,
    "ul'": ul$prime
};
