// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var mkThemeProvider = $foreign.mkThemeProviderImpl;
module.exports = {
    mkThemeProvider: mkThemeProvider
};
