// Generated by purs version 0.13.6
"use strict";
var Interp = function (interp) {
    this.interp = interp;
};
var interpString = new Interp(function (a) {
    return a;
});
var interp = function (dict) {
    return dict.interp;
};
var interpStringFunction = function (dictInterp) {
    return new Interp(function (a) {
        return function (b) {
            return interp(dictInterp)(a + b);
        };
    });
};
var i = function (dictInterp) {
    return interp(dictInterp)("");
};
module.exports = {
    Interp: Interp,
    interp: interp,
    i: i,
    interpString: interpString,
    interpStringFunction: interpStringFunction
};
