// Generated by purs version 0.13.6
"use strict";
var Control_Applicative = require("../Control.Applicative/index.js");
var Control_Bind = require("../Control.Bind/index.js");
var Control_Monad_Error_Class = require("../Control.Monad.Error.Class/index.js");
var Data_Either = require("../Data.Either/index.js");
var Data_Foldable = require("../Data.Foldable/index.js");
var Data_Function = require("../Data.Function/index.js");
var Data_Functor = require("../Data.Functor/index.js");
var Data_Interpolate = require("../Data.Interpolate/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Data_Monoid = require("../Data.Monoid/index.js");
var Data_Show = require("../Data.Show/index.js");
var Data_Symbol = require("../Data.Symbol/index.js");
var Effect = require("../Effect/index.js");
var Effect_Aff = require("../Effect.Aff/index.js");
var Effect_Class = require("../Effect.Class/index.js");
var Effect_Exception = require("../Effect.Exception/index.js");
var JSS = require("../JSS/index.js");
var Milkis = require("../Milkis/index.js");
var React_Basic = require("../React.Basic/index.js");
var React_Basic_DOM = require("../React.Basic.DOM/index.js");
var React_Basic_DOM_Generated = require("../React.Basic.DOM.Generated/index.js");
var React_Basic_Events = require("../React.Basic.Events/index.js");
var React_Basic_Hooks = require("../React.Basic.Hooks/index.js");
var React_Basic_Hooks_Internal = require("../React.Basic.Hooks.Internal/index.js");
var Record_Extra = require("../Record.Extra/index.js");
var Shared_Json = require("../Shared.Json/index.js");
var Simple_JSON = require("../Simple.JSON/index.js");
var Type_Equality = require("../Type.Equality/index.js");
var Yoga_Button_Component = require("../Yoga.Button.Component/index.js");
var Yoga_Card_Component = require("../Yoga.Card.Component/index.js");
var Yoga_Editor = require("../Yoga.Editor/index.js");
var Yoga_Theme_Styles = require("../Yoga.Theme.Styles/index.js");
var compileAndRun = function (fetch) {
    return function (body) {
        return Control_Bind.bind(Effect_Aff.bindAff)(Effect_Aff.attempt(fetch()("/api/compileAndRun")({
            method: Milkis.postMethod,
            body: Simple_JSON.writeJSON(Simple_JSON.recordWriteForeign()(Simple_JSON.consWriteForeignFields(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                return "code";
            }))(Simple_JSON.writeForeignString)(Simple_JSON.nilWriteForeignFields)()()()))(body),
            headers: Milkis.makeHeaders()({
                "Content-Type": "application/json"
            })
        })))(function (response) {
            if (response instanceof Data_Either.Left) {
                return Control_Applicative.pure(Effect_Aff.applicativeAff)(new Data_Either.Left({
                    resultType: "",
                    result: [ {
                        allSpans: [  ],
                        errorCode: "",
                        errorLink: "",
                        filename: "",
                        message: Effect_Exception.message(response.value0),
                        moduleName: Data_Maybe.Nothing.value,
                        position: {
                            endColumn: 0,
                            endLine: 0,
                            startColumn: 0,
                            startLine: 0
                        },
                        suggestion: Data_Maybe.Nothing.value
                    } ]
                }));
            };
            if (response instanceof Data_Either.Right) {
                var v = Milkis.statusCode(response.value0);
                if (v === 200) {
                    return Data_Functor.mapFlipped(Effect_Aff.functorAff)(Control_Bind.bind(Effect_Aff.bindAff)(Milkis.json(response.value0))(Shared_Json.readAff(Simple_JSON.readRecord()(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "code";
                    }))(Simple_JSON.readMaybe(Simple_JSON.readInt))(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "stderr";
                    }))(Simple_JSON.readString)(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "stdout";
                    }))(Simple_JSON.readString)(Simple_JSON.readFieldsNil)()())()())()()))))(Data_Either.Right.create);
                };
                if (v === 422) {
                    return Data_Functor.mapFlipped(Effect_Aff.functorAff)(Control_Bind.bind(Effect_Aff.bindAff)(Milkis.json(response.value0))(Shared_Json.readAff(Simple_JSON.readRecord()(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "result";
                    }))(Simple_JSON.readArray(Simple_JSON.readRecord()(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "allSpans";
                    }))(Simple_JSON.readArray(Simple_JSON.readRecord()(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "end";
                    }))(Simple_JSON.readArray(Simple_JSON.readInt))(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "name";
                    }))(Simple_JSON.readString)(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "start";
                    }))(Simple_JSON.readArray(Simple_JSON.readInt))(Simple_JSON.readFieldsNil)()())()())()())))(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "errorCode";
                    }))(Simple_JSON.readString)(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "errorLink";
                    }))(Simple_JSON.readString)(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "filename";
                    }))(Simple_JSON.readString)(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "message";
                    }))(Simple_JSON.readString)(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "moduleName";
                    }))(Simple_JSON.readMaybe(Simple_JSON.readString))(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "position";
                    }))(Simple_JSON.readRecord()(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "endColumn";
                    }))(Simple_JSON.readInt)(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "endLine";
                    }))(Simple_JSON.readInt)(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "startColumn";
                    }))(Simple_JSON.readInt)(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "startLine";
                    }))(Simple_JSON.readInt)(Simple_JSON.readFieldsNil)()())()())()())()()))(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "suggestion";
                    }))(Simple_JSON.readMaybe(Simple_JSON.readRecord()(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "replaceRange";
                    }))(Simple_JSON.readRecord()(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "endColumn";
                    }))(Simple_JSON.readInt)(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "endLine";
                    }))(Simple_JSON.readInt)(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "startColumn";
                    }))(Simple_JSON.readInt)(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "startLine";
                    }))(Simple_JSON.readInt)(Simple_JSON.readFieldsNil)()())()())()())()()))(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "replacement";
                    }))(Simple_JSON.readString)(Simple_JSON.readFieldsNil)()())()())))(Simple_JSON.readFieldsNil)()())()())()())()())()())()())()())()())))(Simple_JSON.readFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                        return "resultType";
                    }))(Simple_JSON.readString)(Simple_JSON.readFieldsNil)()())()()))))(Data_Either.Left.create);
                };
                return Control_Monad_Error_Class.throwError(Effect_Aff.monadThrowAff)(Effect_Exception.error("Unexpected response code " + Data_Show.show(Data_Show.showInt)(v)));
            };
            throw new Error("Failed pattern match at Yoga.CompileEditor.Component (line 148, column 3 - line 174, column 76): " + [ response.constructor.name ]);
        });
    };
};
var mkCompileEditor = function (fetch) {
    return function __do() {
        var editor = Yoga_Editor.mkEditor();
        var card = Yoga_Card_Component.mkCard();
        var button = Yoga_Button_Component.mkButton()()()()();
        var useStyles = Yoga_Theme_Styles.makeStylesJSS()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
            return "buttons";
        }))()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
            return "card";
        }))()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
            return "cardHidden";
        }))()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
            return "compileButton";
        }))()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
            return "compileError";
        }))()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
            return "editor";
        }))()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
            return "resetButton";
        }))()(Record_Extra.mapRecordCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
            return "runOutput";
        }))()(Record_Extra.mapRecordNil)()())()())()())()())()())()())()())()())(JSS.jssClasses()(function (v) {
            return {
                editor: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "background";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "borderRadius";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "boxShadow";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "boxSizing";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "display";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "flexDirection";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "height";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "marginTop";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "padding";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsNil))))))))))()())({
                    background: v.backgroundColour,
                    boxSizing: "content-box",
                    height: "80%",
                    padding: "20px",
                    marginTop: "0px",
                    borderRadius: "12px",
                    boxShadow: Data_Interpolate.i(Data_Interpolate.interpStringFunction(Data_Interpolate.interpStringFunction(Data_Interpolate.interpStringFunction(Data_Interpolate.interpStringFunction(Data_Interpolate.interpString)))))("22px 22px 24px ")(v.backgroundColourDarker)(", -22px -22px 24px ")(v.backgroundColourLighter),
                    display: "flex",
                    flexDirection: "column"
                }),
                buttons: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "alignSelf";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "display";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "marginBottom";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsNil))))()())({
                    marginBottom: "4px",
                    display: "flex",
                    alignSelf: "flex-end"
                }),
                compileButton: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsNil)()())({}),
                resetButton: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsNil)()())({}),
                card: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "marginLeft";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "marginRight";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "opacity";
                }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "zIndex";
                }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsNil)))))()())({
                    marginLeft: "35px",
                    marginRight: "35px",
                    opacity: 0,
                    zIndex: 0
                }),
                cardHidden: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "opacity";
                }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsNil))()())({
                    opacity: 0
                }),
                compileError: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "color";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "opacity";
                }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "transition";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsNil))))()())({
                    color: v.red,
                    opacity: 1,
                    transition: "opacity 2.0s ease"
                }),
                runOutput: JSS.jss(JSS.jssAbleRecord(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "color";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "opacity";
                }))(JSS.jssAbleInt)()()()(JSS.jssAbleFieldsCons(new Data_Symbol.IsSymbol(function ($dollar__unused) {
                    return "transition";
                }))(JSS.jssAbleString)()()()(JSS.jssAbleFieldsNil))))()())({
                    color: v.green,
                    opacity: 1,
                    transition: "opacity 2.0s ease"
                })
            };
        }))();
        return React_Basic_Hooks.component()()()("CompileEditor")(function (v) {
            return React_Basic_Hooks_Internal.bind(React_Basic_Hooks_Internal.ixBindRender)(React_Basic_Hooks.useState(Data_Maybe.Nothing.value))(function (v1) {
                return React_Basic_Hooks_Internal.bind(React_Basic_Hooks_Internal.ixBindRender)(useStyles({}))(function (classes) {
                    var onLoad = function (e) {
                        return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(Yoga_Editor.setValue(v.initialCode)(e))(function ($dollar__unused) {
                            return v1.value1(Data_Function["const"](new Data_Maybe.Just(e)));
                        });
                    };
                    return React_Basic_Hooks_Internal.bind(React_Basic_Hooks_Internal.ixBindRender)(React_Basic_Hooks.useState(Data_Maybe.Nothing.value))(function (v2) {
                        var setCompileResult = function ($457) {
                            return v2.value1(Data_Function["const"]($457));
                        };
                        var reset = Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(setCompileResult(Data_Maybe.Nothing.value))(function ($dollar__unused) {
                            return Data_Foldable.for_(Effect.applicativeEffect)(Data_Foldable.foldableMaybe)(v1.value0)(Yoga_Editor.setValue(v.initialCode));
                        });
                        var compileResultToString = function (v3) {
                            if (v3 instanceof Data_Maybe.Nothing) {
                                return "";
                            };
                            if (v3 instanceof Data_Maybe.Just && v3.value0 instanceof Data_Either.Left) {
                                return Data_Foldable.intercalate(Data_Foldable.foldableArray)(Data_Monoid.monoidString)("/n")(Data_Functor.mapFlipped(Data_Functor.functorArray)(v3.value0.value0.result)(function (v4) {
                                    return v4.message;
                                }));
                            };
                            if (v3 instanceof Data_Maybe.Just && v3.value0 instanceof Data_Either.Right) {
                                return v3.value0.value0.stdout;
                            };
                            throw new Error("Failed pattern match at Yoga.CompileEditor.Component (line 85, column 31 - line 88, column 35): " + [ v3.constructor.name ]);
                        };
                        var compileResultToClass = function (v3) {
                            if (v3 instanceof Data_Maybe.Nothing) {
                                return classes.cardHidden;
                            };
                            if (v3 instanceof Data_Maybe.Just && v3.value0 instanceof Data_Either.Left) {
                                return classes.compileError;
                            };
                            if (v3 instanceof Data_Maybe.Just && v3.value0 instanceof Data_Either.Right) {
                                return classes.runOutput;
                            };
                            throw new Error("Failed pattern match at Yoga.CompileEditor.Component (line 90, column 30 - line 93, column 44): " + [ v3.constructor.name ]);
                        };
                        var compile = Data_Foldable.for_(Effect.applicativeEffect)(Data_Foldable.foldableMaybe)(v1.value0)(function (ed) {
                            return Control_Bind.discard(Control_Bind.discardUnit)(Effect.bindEffect)(setCompileResult(Data_Maybe.Nothing.value))(function ($dollar__unused) {
                                return function __do() {
                                    var code = Yoga_Editor.getValue(ed)();
                                    return Effect_Aff.launchAff_(Control_Bind.bind(Effect_Aff.bindAff)(compileAndRun(function (dictUnion) {
                                        return Milkis.fetch(fetch)();
                                    })({
                                        code: code
                                    }))(function (res) {
                                        return Effect_Class.liftEffect(Effect_Aff.monadEffectAff)(setCompileResult(new Data_Maybe.Just(res)));
                                    }))();
                                };
                            });
                        });
                        return Control_Applicative.pure(React_Basic_Hooks_Internal.applicativeRender(Type_Equality.refl))(React_Basic.fragment([ React_Basic_DOM_Generated.div()({
                            children: [ React_Basic_DOM_Generated.div()({
                                className: classes.buttons,
                                children: [ React_Basic.element(button)({
                                    buttonType: Yoga_Button_Component.PlainButton.value,
                                    kids: [ React_Basic_DOM.text("Reset") ],
                                    buttonProps: {
                                        onClick: React_Basic_Events.handler_(reset)
                                    },
                                    className: classes.resetButton
                                }), React_Basic.element(button)({
                                    buttonType: Yoga_Button_Component.HighlightedButton.value,
                                    kids: [ React_Basic_DOM.text("Compile") ],
                                    buttonProps: {
                                        onClick: React_Basic_Events.handler_(compile)
                                    },
                                    className: classes.compileButton
                                }) ]
                            }), React_Basic.element(editor)({
                                onLoad: onLoad,
                                height: v.height,
                                language: v.language
                            }) ],
                            className: classes.editor
                        }), React_Basic.element(card)({
                            kids: [ React_Basic_DOM.text(compileResultToString(v2.value0)) ],
                            className: classes.card + (" " + compileResultToClass(v2.value0))
                        }) ]));
                    });
                });
            });
        })();
    };
};
module.exports = {
    mkCompileEditor: mkCompileEditor,
    compileAndRun: compileAndRun
};
