// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var indexOf = $foreign["_indexOf"](Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
var contains = function (pat) {
    var $286 = indexOf(pat);
    return function ($287) {
        return Data_Maybe.isJust($286($287));
    };
};
module.exports = {
    contains: contains,
    indexOf: indexOf,
    singleton: $foreign.singleton,
    length: $foreign.length,
    drop: $foreign.drop
};
