// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
module.exports = {
    abs: $foreign.abs,
    atan2: $foreign.atan2,
    cos: $foreign.cos,
    pow: $foreign.pow,
    round: $foreign.round,
    sin: $foreign.sin,
    sqrt: $foreign.sqrt,
    remainder: $foreign.remainder,
    pi: $foreign.pi
};
