// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var Data_Foldable = require("../Data.Foldable/index.js");
var Data_Function = require("../Data.Function/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Data_Tuple = require("../Data.Tuple/index.js");
var zip = $foreign.zipWith(Data_Tuple.Tuple.create);
var uncons = $foreign["uncons'"](Data_Function["const"](Data_Maybe.Nothing.value))(function (x) {
    return function (xs) {
        return new Data_Maybe.Just({
            head: x,
            tail: xs
        });
    };
});
var index = $foreign.indexImpl(Data_Maybe.Just.create)(Data_Maybe.Nothing.value);
var head = function (xs) {
    return index(xs)(0);
};
var fromFoldable = function (dictFoldable) {
    return $foreign.fromFoldableImpl(Data_Foldable.foldr(dictFoldable));
};
module.exports = {
    fromFoldable: fromFoldable,
    head: head,
    uncons: uncons,
    index: index,
    zip: zip,
    length: $foreign.length,
    cons: $foreign.cons,
    snoc: $foreign.snoc,
    zipWith: $foreign.zipWith
};
