// Generated by purs version 0.13.6
"use strict";
var IxBind = function (IxApply0, ibind) {
    this.IxApply0 = IxApply0;
    this.ibind = ibind;
};
var ibind = function (dict) {
    return dict.ibind;
};
module.exports = {
    IxBind: IxBind,
    ibind: ibind
};
