// Generated by purs version 0.13.6
"use strict";
var Control_Applicative = require("../Control.Applicative/index.js");
var Data_Either = require("../Data.Either/index.js");
var Data_List_Types = require("../Data.List.Types/index.js");
var Data_Show = require("../Data.Show/index.js");
var Effect_Aff = require("../Effect.Aff/index.js");
var Effect_Class = require("../Effect.Class/index.js");
var Effect_Exception = require("../Effect.Exception/index.js");
var Foreign = require("../Foreign/index.js");
var Simple_JSON = require("../Simple.JSON/index.js");
var orThrow = function (dictShow) {
    return Data_Either.either((function () {
        var $390 = Effect_Class.liftEffect(Effect_Aff.monadEffectAff);
        var $391 = Data_Show.show(dictShow);
        return function ($392) {
            return $390(Effect_Exception["throw"]($391($392)));
        };
    })())(Control_Applicative.pure(Effect_Aff.applicativeAff));
};
var readAff = function (dictReadForeign) {
    var $393 = orThrow(Data_List_Types.showNonEmptyList(Foreign.showForeignError));
    var $394 = Simple_JSON.read(dictReadForeign);
    return function ($395) {
        return $393($394($395));
    };
};
module.exports = {
    readAff: readAff
};
