// Generated by purs version 0.13.6
"use strict";
var Control_Category = require("../Control.Category/index.js");
var Control_Parallel_Class = require("../Control.Parallel.Class/index.js");
var Data_Foldable = require("../Data.Foldable/index.js");
var parTraverse_ = function (dictParallel) {
    return function (dictFoldable) {
        return function (f) {
            var $112 = Control_Parallel_Class.sequential(dictParallel);
            var $113 = Data_Foldable.traverse_(dictParallel.Applicative1())(dictFoldable)((function () {
                var $115 = Control_Parallel_Class.parallel(dictParallel);
                return function ($116) {
                    return $115(f($116));
                };
            })());
            return function ($114) {
                return $112($113($114));
            };
        };
    };
};
var parSequence_ = function (dictParallel) {
    return function (dictFoldable) {
        return parTraverse_(dictParallel)(dictFoldable)(Control_Category.identity(Control_Category.categoryFn));
    };
};
module.exports = {
    parTraverse_: parTraverse_,
    parSequence_: parSequence_
};
