// Generated by purs version 0.13.6
"use strict";
var Effect_Class = require("../Effect.Class/index.js");
var Effect_Console = require("../Effect.Console/index.js");
var log = function (dictMonadEffect) {
    var $328 = Effect_Class.liftEffect(dictMonadEffect);
    return function ($329) {
        return $328(Effect_Console.log($329));
    };
};
module.exports = {
    log: log
};
