// Generated by purs version 0.13.6
"use strict";
var Data_Semigroup = require("../Data.Semigroup/index.js");
var Monoid = function (Semigroup0, mempty) {
    this.Semigroup0 = Semigroup0;
    this.mempty = mempty;
};
var monoidString = new Monoid(function ($dollar__unused) {
    return Data_Semigroup.semigroupString;
}, "");
var mempty = function (dict) {
    return dict.mempty;
};
var guard = function (dictMonoid) {
    return function (v) {
        return function (v1) {
            if (v) {
                return v1;
            };
            if (!v) {
                return mempty(dictMonoid);
            };
            throw new Error("Failed pattern match at Data.Monoid (line 73, column 1 - line 73, column 49): " + [ v.constructor.name, v1.constructor.name ]);
        };
    };
};
module.exports = {
    Monoid: Monoid,
    mempty: mempty,
    guard: guard,
    monoidString: monoidString
};
