// Generated by purs version 0.13.6
"use strict";
var $foreign = require("./foreign.js");
var Container_Component = require("../Container.Component/index.js");
var Data_Functor = require("../Data.Functor/index.js");
var Data_Maybe = require("../Data.Maybe/index.js");
var Effect = require("../Effect/index.js");
var Effect_Console = require("../Effect.Console/index.js");
var React_Basic = require("../React.Basic/index.js");
var React_Basic_DOM = require("../React.Basic.DOM/index.js");
var Web_DOM_NonElementParentNode = require("../Web.DOM.NonElementParentNode/index.js");
var Web_HTML = require("../Web.HTML/index.js");
var Web_HTML_HTMLDocument = require("../Web.HTML.HTMLDocument/index.js");
var Web_HTML_Window = require("../Web.HTML.Window/index.js");
var Yoga_Theme = require("../Yoga.Theme/index.js");
var Yoga_Theme_Default = require("../Yoga.Theme.Default/index.js");
var main = function __do() {
    var v = Container_Component.mkContainer();
    var appEl = React_Basic.element(v)({
        theme: Yoga_Theme.fromTheme(Yoga_Theme_Default.darkTheme),
        kids: [  ]
    });
    if ($foreign.isServerSide) {
        return Data_Functor["void"](Effect.functorEffect)(Effect_Console.log($foreign.renderToString(appEl)))();
    };
    return Data_Functor["void"](Effect.functorEffect)(function __do() {
        var v1 = Web_HTML.window();
        var v2 = Web_HTML_Window.document(v1)();
        var node = Web_HTML_HTMLDocument.toNonElementParentNode(v2);
        var v3 = Web_DOM_NonElementParentNode.getElementById("app")(node)();
        var element$prime = Data_Maybe.fromJust()(v3);
        return React_Basic_DOM.render(appEl)(element$prime)();
    })();
};
module.exports = {
    main: main
};
